pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:yitf/test-github-mirror.git
          - cd RepoName.git
          - git push --mirror git@github.com:fenosoa-rhj/test_pipeline.git